### ISSUE TITLE
EnableCF=false cannot handle 64-bit integer.

### ISSUE THREAD

**Issue by hyoklee** [OPENDAP/hdf5_handler#5]
The test file is from LIGO. 

http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.html

```
OUCH!

Something Bad Happened On This Server.

The specific error message associated with your request was:

libdap exception building response: error_code = 1002: An internal error was encountered in h5get.cc at line 1274: Unsupported HDF5 64-bit Integer type:/meta/Duration Please report this to support@opendap.org
```

Data is available here:

http://54.174.38.12/thredds/fileServer/testAll/hpd/L-L1_LOSC_4_V1-931069952-4096.h5

**Comment by hyoklee** [comment]
Here's how data is organized.

![screen shot 2016-02-16 at 9 59 34 am](https://cloud.githubusercontent.com/assets/4994401/13081915/3a992282-d494-11e5-9967-d6ed028b464f.png)

**Comment by kyang2014** [comment]
DAP2 doesn't support 64-bit integer. That's a known limitation.

**Comment by hyoklee** [comment]
Doesn't DAP4 support 64-bit integer?

**Comment by ndp-opendap** [comment]
Yes. Yes it does. But you are asking for a DAP2 response.

**Comment by hyoklee** [comment]
How can I ask for a DAP4 response?

**Comment by hyoklee** [comment]
http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.dmr

doesn't show any variables.

**Comment by ndp-opendap** [comment]
That is a bug in the Form. Stop using a browser, or specifically ask for XML:

curl http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.dmr

OR

http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.dmr.xml

**Comment by hyoklee** [comment]
OK. How can I retrieve /meta/Duration data values in ASCII using DAP4 call and check values with browser?

**Comment by ndp-opendap** [comment]
When you use a browser to access the server you are engaging a lot of top level machinery that you may not realize. This is because the browser always submits an "Accept" header, and all of DAP4 respects that and tries to deliver the most preferred result. Additionally, the HTML Data request form is the default HTML encoding of the DMR response. As you discovered this has some bugs - the one you found is a by product of the fact that the test dataset that makes up the hdf5_handler test data that is used by autotest/Travis-CI etc. has no Groups and thus this is the first time I have seen it used with a dataset that contains Groups. https://opendap.atlassian.net/browse/BES-115

More importantly, what are you trying to test? The HTML Data Request Form? The HTTP content negotiation stack? Or, are you trying to test the hdf5_handler? I suggest using command line curl to test the handlers because its behavior is more predictable, largely due to the fact that you will have explicit control over the Accept header. You simply can't ignore the HTTP transport component when working with DAP4  and curl is a great way to exercise some control so that you are testing the stuff you intend to test.

Building DAP4 URLs is similar to building DAP2 URLs but we utilize additional suffixes on the primary DAP4 suffixes to explicitly request alternate encodings: http://docs.opendap.org/index.php/DAP4:_Specification_Volume_2#DAP4_Resource_Roles_and_Media_Types

You can "preview"  a data result by constraining the DMR response:
http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.dmr.xml?dap4.ce=/meta/Duration

You can get the data by asking for the data response:
http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.dap?dap4.ce=/meta/Duration

And you can get CSV values by asking for an alternate encoding of the dap4 data response:

http://54.174.38.12:8888/opendap/data/HPD/hpd/L-L1_LOSC_4_V1-931069952-4096.h5.dap.csv?dap4.ce=/meta/Duration

(Note that this last should really be ".txt" suffix and not ".csv" according to the specification - I'll need to change that bit)

**Comment by hyoklee** [comment]
May I get an account for https://opendap.atlassian.net/ so that I can check BES-115 issue?

**Comment by ndp-opendap** [comment]
You have one that you have never used.

user name: hyoklee  
email: hyoklee@hdfgroup.org 

Try using the "I forgot my password" link.

**Comment by hyoklee** [comment]
Thanks. I can login but can't browse BES project issue.
![opendap_jira](https://cloud.githubusercontent.com/assets/4994401/13096340/5e2399ea-d4de-11e5-89b3-0e56fd706524.png)

**Comment by ndp-opendap** [comment]
I added you to the developers group, you should be able to see it now.

**Comment by hyoklee** [comment]
Thanks, I can see the issue. I'll close this ticket.
